# 默认设置
default:
  groupCD: 500 # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 2000 # 群聊中个人操作冷却时间，单位毫秒

  onlyReplyAt: 0 # 是否只仅关注主动@机器人的消息， 0-否 1-是 2-触发用户非主人只回复@机器人的消息及特定前缀的消息，主人免前缀
  botAlias:
    - m

  addLimit: 0 # 是否限制添加消息 0-所有群员 1-群管理员 2-主人
  addPrivate: 1 # 是否允许私聊添加
  addReply: 1 # 是否回复触发消息
  addAt: 0 # 是否提及触发用户
  addRecall: 0 # 是否撤回回复消息

  enable: []
  disable:
    - 禁用示例
    - 支持多个
    - 阿里云盘
    - 百度网盘
    - Markdown
    - 图片修复
    - 图片背景去除

# Bot单独设置
114514:default:
  onlyReplyAt: 1
  botAlias:
    - m

# 群单独设置
123456:
  groupCD: 500
  singleCD: 2000

# [Bot:群]单独设置
114514:123456:
  enable:
  disable:
2660750139:983299064:
  __place__: 0
  onlyReplyAt: 1
  botAlias:
    - m
2660750139:784393804:
  __place__: 0
  onlyReplyAt: 1
  botAlias:
    - m
    
